[project]
authors = ["Hameer Abbasi <2190658+hameerabbasi@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mlir-tutorial"
platforms = ["osx-arm64"]
version = "0.1.0"

[activation.env]
PATH = "${PWD}/externals/llvm-project/build/bin:${PWD}/build-ninja/tools:${PATH}"

[tasks]
clone = { cmd = "git submodule update --init --recursive" }
build = { cmd = "scripts/build.sh", depends-on="clone" }
test = { cmd = "scripts/test.sh", depends-on = ["build"] }

lit = { cmd = "externals/llvm-project/build/bin/llvm-lit" }

[dependencies]
compilers = ">=1.9.0,<2"
cmake = ">=3.31.4,<4"
ninja = ">=1.12.1,<2"
ccache = ">=4.10.1,<5"
python = ">=3.13.1,<3.14"
